description: A process description.
content:
  application/json:
    schema:
      $ref: "../schemas/process_swagger.yaml"
    examples:
      processDecription:
        summary: A Process Description example
        externalValue: "../../examples/json/ProcessDescription.json"
